### PR TITLE
Make app code follow clean coding

### PR DESCRIPTION
**Pull request by bittner**
The changes in this PR attempt to make the app code more self-explanatory. Instead of comments we're using docstrings, functions do "only one thing", we clean up all unneeded code (unused imports). 

BeeWare users should be inspired by self-explanatory, clean code. The rest is in the documentation.

**Note:** After this is merged, the [related documentation](https://github.com/beeware/briefcase/blob/master/docs/tutorial/tutorial-0.rst) needs be aligned again, too.

### CODE REVIEW

**Comment by freakboy3742** [comment]
Thanks for the contribution, but I disagree that these changes make anything "cleaner". 

The purpose of the Briefcase template is to bootstrap a project as quickly as possible. It gives the end-user a minimal working project, including imports that almost every project will need. Including additional complexity in a bootstrap gives the impression that there is a coding convention that all projects *need* to follow, when no such convention exists. If every novice user gets "make_main_window()" and "make_main_content()" in their stub, at least some of them are going to ascribe significance to those names, in those places, and then ask why those methods need to exist, and whether they can add their own, and so on.

Don't get me wrong - refactoring submethods in this way will often be a good idea - but when we provide a template, we need to be careful about the message we're communicating with that template.

**Comment by bittner** [comment]
> including imports that almost every project will need

That is fine, I can bring that back in.

> Including additional complexity in a bootstrap

I believe, it's the contrary. These changes increase readability. It's an implementation of PEP 20, code must be beautiful and self-explanatory (Clean code is a perfect match of what PEP 20 says).

We need to provide developers with a good place to start _software development_ from, not just a template _to hack a solution_. The Python community deserves this!

Maybe I should have opened an issue first to discuss matters?

**Comment by freakboy3742** [comment]
I'm sorry, but I disagree. Adding submethods in this way adds 2 levels of indirection for something that is only 4 instructions to start with.

Templates like this one serve two purposes - they provide a basis for future development, but they also communicate things that we, as the library maintainers, think the user should know about. Adding a method like "make_main_content" imposes a cognitive burden on new users. They need to ask "Why is it there?" What is the significance of this name? Do I have to provide this method? 

It is not even a *slight* stretch in my mind to imagine a world where developers end up defining *empty* "make_main_content()" methods because they think the method is needed by the framework, because the initial template *explicitly told them* it was needed. 

We could certainly do a better job of encouraging good code use, reuse and structure - but IMHO the place for that is the code examples of full projects, not the initial project template.

In terms of project procedure: there's no problem opening a PR for this sort of thing. You probably want to start with an issue and discussion if the implementation is going to be complex; but in the case of a relatively straightforward change like this one, a PR serves as a good starting point for describing exactly what you have in mind.

**Comment by bittner** [comment]
Sorry, Russel, that my PR caused you personal anger. I should have avoided that and discuss this in an issue first. I hoped that "being a welcoming community" also stretched to contributions, and that we would discuss the PR before it would be closed unmerged (in a mutual agreement). I should have known better and I apologize.

Let me just stress that, specifically, I'm not happy with the `make_foo` functions _at all_. I had hoped we'd come up with either a better naming or not using them at all, while the PR would have gone forward.

And while I see value in the explanations you provide I believe we should treat each other with respect, help each other along with contributions, strive to understand each other's motivations, and show the world that the Python community is a welcoming community. -- _I could have been a first-time contributor. (Well, true, I am not -- that's why I apologized.)_

**Comment by freakboy3742** [comment]
You certainly haven't caused me "personal anger", and if my response gave you that impression, I sincerely apologize. I aspire to BeeWare (and the Python community) being welcoming to people of all backgrounds and experience levels, both as contributors and as users. If that hasn't been your experience, then that's my failing, not yours. If you have any suggestions about how I could have managed this discussion better, please let me know.

I'm very keen to discuss any suggestion. However, that doesn't mean every suggestion will be accepted. In this case, I closed the PR because I couldn't see any obvious path forward. I couldn't see a case where "if only this one detail was slightly different, I would merge". I can see how closing the ticket perhaps comes off as "anger". I can only say that from my perspective, it's only an indicator that at least for now, I've made a decision as a project lead. However, nothing in Github (or most other ticket systems for that matter) is irreversible. You should feel free to continue to make your case if you feel there's some aspect of the problem that I've missed.

For the benefit of discussion (and, to demonstrate in some small way that there's no ill-will on my part), I'm happy to reopen this ticket. However, I will state in advance that I'm still not sure I see what the path forward is. Either you believe that factoring the template into submethods is "cleaner", or you don't; and I don't. It's not just a matter of naming; it's a pedagogical issue (which I've already detailed).

I'm intrigued by your suggestion that your aims could be met by not using these functions at all. I'm having imagining out what this patch would look like *without* adding the extra methods. If you've got other ideas - please, by all means let me know what they are.

**Comment by bittner** [comment]
Russell, I've taken your thoughts into account, I think. The code doesn't need comments this way. I hope this is a better ground for discussion, now.

**Comment by bittner** [comment]
Thanks, Russell! :+1:

**Pull request merged**
