### PR TITLE
Update Toga projects to use webkit2.

### PR DESCRIPTION
**Pull request by freakboy3742**
The GTK Webkit libraries installed in Toga projects appear to be a hangover from the 16.04 days; the webkit libraries are still present on 18.04, but webkit2 gives a much better experience.

Refs beeware/briefcase#1029.

## PR Checklist:

- [x] All new features have been tested
- [x] All new features have been documented
- [x] I have read the **CONTRIBUTING.md** file
- [x] I will abide by the code of conduct

### CODE REVIEW

**Review by rmartin16 — COMMENTED** [review]
hmm....youre able to install these `webkit2` packages? I can't find them on Ubuntu 18.04.

```
Step 14/15 : RUN apt-get update -y &&     apt-get install --no-install-recommends -y ${SYSTEM_REQUIRES}
 ---> Running in 4966c0171015
Hit:1 http://security.ubuntu.com/ubuntu bionic-security InRelease
Hit:2 http://ppa.launchpad.net/deadsnakes/ppa/ubuntu bionic InRelease
Hit:3 http://archive.ubuntu.com/ubuntu bionic InRelease
Hit:4 http://archive.ubuntu.com/ubuntu bionic-updates InRelease
Hit:5 http://archive.ubuntu.com/ubuntu bionic-backports InRelease
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...
E: Unable to locate package libwebkitgtk2-4.0-dev
E: Couldn't find any package by glob 'libwebkitgtk2-4.0-dev'
E: Couldn't find any package by regex 'libwebkitgtk2-4.0-dev'
The command '/bin/sh -c apt-get update -y &&     apt-get install --no-install-recommends -y ${SYSTEM_REQUIRES}' returned a non-zero code: 100
>>> Return code: 100
Building Docker image...

Error building Docker container image for gtk.
```

**Comment by freakboy3742** [comment]
> hmm....youre able to install these `webkit2` packages? I can't find them on Ubuntu 18.04.

Dammit... I retyped, rather than copy-and-pasting the dependency. It should have been `libwebkit2gtk-4.0-dev`. Fix incoming.

**Comment by freakboy3742** [comment]
I've also added a CI configuration (copied from Briefcase) to ensure that we can build every meaningful app configuration. This would have caught the GTK package name error.

**Review by rmartin16 — APPROVED** [review]
Discussed with @freakboy3742. Despite the current situation with `linuxdeploy-plugin-gtk` (see beeware/briefcase#1029), these libraries should still be updated.

Additionally, given this is probably at least the third place we're building all the different apps in CI, a future state should consolidate this to prevent all this CI duplication; this is non-trivial right now since they are all slightly different.

**Pull request merged**
